### ISSUE TITLE
Washed out colors

### ISSUE THREAD

**Issue by sogen** [MagicSketch/MagicMirror#36]
Hi, just noticed that colors in the mirror are washed out, attached is screenshot and example zipped .sketch file

[magic mirror bug - washed out colors.sketch.zip](https://github.com/jamztang/MagicMirror/files/226172/magic.mirror.bug.-.washed.out.colors.sketch.zip)

![screen shot 2016-04-19 at 10 12 12 am](https://cloud.githubusercontent.com/assets/2784323/14644303/3b8104bc-0617-11e6-89d5-0110b8896d5c.png)

**Comment by jamztang** [comment]
Thanks will look at it!

**Comment by jamztang** [comment]
Had addressed this while ago, probably somewhere at v2.0.9.
Should have close this earlier.

As a side note, color difference might still happen but that's due to Sketch color display in Image Fill, it looks like there's no color profiling calibration in Image Fill. But when you export the image, it turns out that the color will be the same as original.

Ticket has been raised to the team, will follow up from [there](http://sketchplugins.com/d/254-color-mismatch-issue-in-image-fill)
