### ISSUE TITLE
Plugin is "damaged and can't be opened" on macOS Catalina, Sketch 58

### ISSUE THREAD

**Issue by brod-ie** [MagicSketch/MagicMirror#91]
<img width="532" alt="Screenshot 2019-10-31 at 22 48 36" src="https://user-images.githubusercontent.com/1520630/67991312-b235a280-fc30-11e9-9ef6-f88c7ac68b0d.png">

**Comment by brod-ie** [comment]
https://sketchplugins.com/d/1469-plugin-with-native-framework-can-t-be-opened-in-catalina

> From 10.15 onwards all frameworks loaded into Sketch need to be signed.

**Comment by brod-ie** [comment]
https://twitter.com/steipete/status/1145674670886281216

Disabling gatekeeper also doesn't help

**Comment by gjerlow** [comment]
Hi @brod-ie, do you still have this issue? I can't get it to run myself, and I've tested with Sketch 59.1 as well..

**Comment by gjerlow** [comment]
I got this from support now:

> I have been advised by the relevant team that if you download the latest plugin directly from our Website, it will show damage, however, if you download it via Sketch's update dialog, things will work

> The work around for now is to download version 3.6.6 first and let Sketch update the plugin

To get it working I had to rollback to v 57 of Sketch as well. I haven't tried switching back to v 59 yet.

**Comment by SimplyPhy** [comment]
Steps to solve (workaround provided by @gjerlow ):
1. download Sketch 57.1 from https://www.sketch.com/updates/
2. download Magic Mirror 3.6.6 from https://github.com/MagicSketch/MagicMirror/releases
3. open sketch 57.1 & close sketch sketch 58+
4. install (double click) Magic Mirror 3.6.6
5. when prompted to delete Magic Mirror 3.6.6 because it's damaged, click cancel every time (it will ask several times)
6. close and re-open sketch 57.1
7. open doc, and `update available for plugin` button should appear in top right of Sketch
8. update Magic Mirror to version 58
9. enable Magic Mirror in Plugins dropdown
10. close Sketch 57.1, open Sketch 58+

Success!

**Comment by brod-ie** [comment]
@SimplyPhy worked a treat, some screenshots which may be helpful to others:

1. Opening Sketch 57.1 with MagicSketch 3.6.6 installed prompted:
    <img width="382" alt="Screenshot 2019-11-26 at 13 08 02" src="https://user-images.githubusercontent.com/1520630/69636283-2ad02900-104e-11ea-99e5-96868ecbfcc1.png">
1. Clicking through:
    <img width="632" alt="Screenshot 2019-11-26 at 13 08 06" src="https://user-images.githubusercontent.com/1520630/69636298-2c99ec80-104e-11ea-9e0c-dc5c620ecc46.png">
3. Updated and opened (now) Sketch 60.1 and it works! 🎉

**Comment by jcalvarezjr** [comment]
Thanks a bunch! This worked!
